- name: Configure Nginx on EC2
  hosts: flight-app-instance
  become: yes
  
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Custom Index Page
      copy:
        content: |
          <h1>Nginx configured via Ansible</h1>
        dest: /usr/share/nginx/html/index.html
